apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: 982081045114.dkr.ecr.eu-west-3.amazonaws.com/web-app/web-app
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/appdb
        - name: SPRING_DATASOURCE_USERNAME
          value: mehdi
        - name: SPRING_DATASOURCE_PASSWORD
          value: mehdi123
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: web-app
spec:
  type: LoadBalancer
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
